alias        rm="rm -i"
alias        mv="mv -i"
alias        cp="cp -i"
alias       cls="clear" 
alias        la="ls -a"
alias        ll="ls -l"
alias       lla="ls -la"
alias      llah="ls -lah"
alias      grep="grep -E --color"
alias       sed="sed -r"
alias      sudo="sudo "
alias    unsudo="sudo -k"
alias        rl="readlink -f"
alias     xargs="xargs "
alias        bc="bc -l"
alias        LS="sl"
alias      rdig="dig -x"
alias      sdig="dig +short"
alias     iperf="iperf3"
alias highlight="highlight -s candy"
alias      cath="highlight"
alias      hcat="cath"
alias      catb="bat"
alias      bcat="catb"
alias      batp="bat -P"
alias      catl="lolcat"
alias      lcat="catl"
alias  cpufetch="cpufetch | lolcat -f"
alias  linguist="github-linguist"

# exa
alias    l="exa -lgh"
alias   lx="exa"
alias  lxa="l -a"
alias  lxt="l -T"
alias lxta="lxt -a"
alias lxat="lxta"

# ripgrep
alias    rg="rg -g '!*.svg'" # exclude SVG
alias   rgh="rg --hidden"
alias   rgi="rg -i"
alias   rgl="rg -L"
alias  rghi="rgh -i"
alias  rghl="rgh -L"
alias  rgih="rghi"
alias  rgil="rgi -L"
alias  rglh="rghl"
alias  rgli="rgil"
alias rghil="rghi -L"
alias rghli="rghil"
alias rgihl="rghil"
alias rgilh="rghil"
alias rglhi="rghil"
alias rglih="rghil"

