#!/bin/bash

#alias zypphis='cut -d '\''|'\'' -f 1-4 -s --output-delimiter '\'' | '\'' /var/log/zypp/history | grep -v '\'' radd '\'''

cut -d '|' -f 1-4 -s --output-delimiter ' | ' /var/log/zypp/history #| grep -v "'" radd "'"
