#!/bin/sh

# Show zypper history
#
# Put this file in /usr/lib/zypper/commands
# Call as zypper history

cut                        \
  -d '|'                   \
  -f 1-4                   \
  --output-delimiter ' | ' \
  -s                       \
  /var/log/zypp/history    \
| grep -v ' radd '         \
| column -t -s '|'

