# completely completion                                    -*- shell-script -*-

# This bash completions script was generated by
# completely (https://github.com/dannyben/completely)
# Modifying it manually is not recommended

_completely_completions() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local compline="${COMP_WORDS[@]:1:$COMP_CWORD-1}"

  case "$compline" in
    'generate'*)
      while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help" -- "$cur" )
      ;;

    'preview'*)
      while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help" -- "$cur" )
      ;;

    'init'*)
      while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help" -- "$cur" )
      ;;

    'test'*)
      while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help" -- "$cur" )
      ;;

    *)
      while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "init preview generate test" -- "$cur" )
      ;;

  esac
} &&
complete -F _completely_completions completely

# ex: filetype=sh
