# odrive completion                                        -*- shell-script -*-

# This bash completions script was generated by
# completely (https://github.com/dannyben/completely)
# Modifying it manually is not recommended

_odrive_completions() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local compline="${COMP_WORDS[@]:1:$COMP_CWORD-1}"

  case "$compline" in
    'placeholderthreshold'*)
      while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help never small medium large always" -- "$cur" )
      ;;

    'autounsyncthreshold'*)
      while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help never day week month" -- "$cur" )
      ;;

    'autotrashthreshold'*)
      while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help never immediately fifteen hour day" -- "$cur" )
      ;;

    'foldersyncrule'*)
      while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help --expandsubfolders" -- "$cur" )
      ;;

    'encpassphrase'*)
      while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help --initialize" -- "$cur" )
      ;;

    'authenticate'*)
      while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help" -- "$cur" )
      ;;

    'removebackup'*)
      while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help" -- "$cur" )
      ;;

    'restoretrash'*)
      while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help" -- "$cur" )
      ;;

    'xlthreshold'*)
      while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help never small medium large xlarge" -- "$cur" )
      ;;

    'deauthorize'*)
      while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help" -- "$cur" )
      ;;

    'diagnostics'*)
      while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help" -- "$cur" )
      ;;

    'emptytrash'*)
      while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help" -- "$cur" )
      ;;

    'syncstate'*)
      while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help --textonly" -- "$cur" )
      ;;

    'backupnow'*)
      while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help" -- "$cur" )
      ;;

    'shutdown'*)
      while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help" -- "$cur" )
      ;;

    'unmount'*)
      while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help" -- "$cur" )
      ;;

    'refresh'*)
      while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help" -- "$cur" )
      ;;

    'backup'*)
      while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help" -- "$cur" )
      ;;

    'stream'*)
      while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help --remote" -- "$cur" )
      ;;

    'unsync'*)
      while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help --force" -- "$cur" )
      ;;

    'status'*)
      while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help --mounts --backups --sync_requests --uploads --downloads --background --trash --waiting --not_allowed" -- "$cur" )
      ;;

    'mount'*)
      while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help" -- "$cur" )
      ;;

    'sync'*)
      while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "--help --recursive --nodownload" -- "$cur" )
      ;;

    *)
      while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "authenticate mount unmount backup removebackup sync stream refresh unsync xlthreshold autounsyncthreshold autotrashthreshold placeholderthreshold foldersyncrule encpassphrase syncstate status deauthorize diagnostics backupnow emptytrash restoretrash shutdown" -- "$cur" )
      ;;

  esac
} &&
complete -F _odrive_completions odrive

# ex: filetype=sh
